
favicon.ico: favicon.png
	convert -background none favicon.png \
			\( -clone 0 -resize 64x64 \) \
			\( -clone 0 -resize 48x48 \) \
			\( -clone 0 -resize 32x32 \) \
			\( -clone 0 -resize 16x16 \) \
			-delete 0 favicon.ico
